<?php

namespace ElsassSeeraiwer\ESArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	public function getAllByCount()
	{
		$em = $this->getEntityManager();

		$query = $em->createQuery(
			"SELECT t, SIZE(t.articles) as a
			FROM ElsassSeeraiwerESArticleBundle:Tag t
			WHERE SIZE(t.articles) > 0
			ORDER BY a DESC");

		$result = $query->getResult();

		return $result;
	}
}
